navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "markdown/readme.md", title: "Markdown"}
  - {file: "README.md", title: "Original page"}
  - {file: "code.md", title: "Code"}
  - {file: "rust/readme.md", title: "Rust"}

theme: jekyll-theme-cayman
