navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "markdown/readme.md", title: "Markdown"}
  - {file: "README.md", title: "About"}
  - {file: "rust/readme.md", title: "Rust"}
  - {file: "pixelart/readme.md", title: "Pixel Art"}
  - {file: "IED/readme.md", title: "ESP32 as IED"}
  - {file: "computer_architecture/readme.md", title: "Computer Architecture"}
  - {file: "unthemed.html", title: "Unthemed"}


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

#logo: "/steam.png"
aux_links:
  "Portefolio on GitHub":
    - "https://github.com/ninja-spotted/Portefolio"
  "Other Example":
    - "https://youtube.com/"
  "Linux Game":
    - "https://overthewire.org/wargames/bandit/bandit0.html"

remote_theme: just-the-docs/just-the-docs
#remote_theme: 
color_scheme: dark
