navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "markdown/readme.md", title: "Markdown"}
  - {file: "README.md", title: "About"}
  - {file: "rust/readme.md", title: "Rust"}
  - {file: "pixelart/readme.md", title: "Pixel Art"}
  - {file: "IED/readme.md", title: "ESP32 as IED"}
  - {file: "computer_architecture/readme.md", title: "Computer Architecture"}

#logo: "/steam.png"
aux_links:
  "Portefolio on GitHub":
    - "https://github.com/Ninja-Spotted/Portefolio"

remote_theme: just-the-docs/just-the-docs
#remote_theme: mmistakes/minimal-mistakes
color_scheme: dark
